name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest-cov

      # Set DJANGO_SETTINGS_MODULE environment variable
      - name: Set Django Settings
        run: |
         export DJANGO_SETTINGS_MODULE=system_monitor.test_settings
         echo "DJANGO_SETTINGS_MODULE=system_monitor.settings" >> $GITHUB_ENV

      # Run tests with coverage
      - name: Run Tests with Coverage
        env:
          DJANGO_SETTINGS_MODULE: "system_monitor.settings"
        run: |
          coverage run -m unittest discover  # or pytest if you prefer
          coverage report  # Optional, you can display a simple text report
          coverage html  # Optional, generates an HTML report for local inspection

      # Lint with Flake8
      - name: Lint Code
        run: |
          pip install flake8
          flake8 .

      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml

